language: go

go:
  - 1.11.5
  - 1.12.3

env:
  - GO111MODULE=on

before_install:
  - go get -u github.com/kisielk/errcheck
  - go get github.com/mattn/goveralls

script:
  - errcheck
  - goveralls -service=travis-ci
